# Generated by Django 5.0.2 on 2024-09-02 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orderitem_unique_product_alter_cart_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_coupon',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_temp_cart',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'coupon'), name='unique_coupon'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('payment', False)), fields=('user', 'payment'), name='unique_temp_cart'),
        ),
    ]
