# Generated by Django 5.0.2 on 2024-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderitem_customer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('payment', False)), fields=('customer', 'payment'), name='unique_temp_cart'),
        ),
    ]
