# Generated by Django 5.0.2 on 2024-08-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_feedback_reaction_reaction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
